=== yoseasoft/com.novaframework.unity.test/Editor Default Resources/Config/repo_manifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- 类型定义 -->

    <xs:complexType name="environment-variable-type">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="system-path-type">
        <xs:sequence>
            <xs:element name="local-path" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="defaultValue" type="xs:string"/>
                    <xs:attribute name="title" type="xs:string"/>
                    <xs:attribute name="required" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="assembly-loadable-strategy-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Module"/>
            <xs:enumeration value="Game"/>
            <xs:enumeration value="Shared"/>
            <xs:enumeration value="Hotfix"/>
            <xs:enumeration value="Compile"/>
            <xs:enumeration value="Tutorial"/>
            <xs:enumeration value="Test"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="package-type">
        <xs:sequence>
            <xs:element name="git-repository">
                <xs:complexType>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="assembly-definition" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="loadable-strategy" type="assembly-loadable-strategy-type" minOccurs="1" maxOccurs="unbounded" nillable="false"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="order" type="xs:integer" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="dependencies" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference-package" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="repulsions" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="reference-package" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="assets-path" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
    </xs:complexType>

    <!-- 元素定义 -->

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="environment-variable" type="environment-variable-type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="system-path" type="system-path-type" minOccurs="0" maxOccurs="1"/>
                <xs:element name="package" type="package-type" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== yoseasoft/com.novaframework.unity.test/Editor Default Resources/Config/repo_manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repo_manifest.xsd">
    <!-- 环境参数设置 -->

    <environment-variable name="REPO_URL" value="https://github.com/yoseasoft"/>

    <system-path>
        <local-path name="ORIGINAL_RESOURCE_PATH" defaultValue="Assets/_Resources" title="原始资源目录" required="true"/>
        <local-path name="SOURCE_CODE_PATH" defaultValue="Assets/Sources" title="源码目录" required="true"/>
        <local-path name="SCRIPT_FILE_PATH" defaultValue="Assets/LuaScripts" title="脚本目录"/>
        <local-path name="AOT_LIBRARY_PATH" defaultValue="Assets/_Resources/Aot" title="预编译库目录" required="true"/>
        <local-path name="LINK_LIBRARY_PATH" defaultValue="Assets/_Resources/Code" title="链接库目录" required="true"/>
        <local-path name="CONTEXT_PATH" defaultValue="Assets/_Resources/Context" title="环境文件目录"/>
        <local-path name="CONFIG_PATH" defaultValue="Assets/_Resources/Config" title="配置文件目录"/>
        <local-path name="PROTOCOL_PATH" defaultValue="Assets/_Resources/Protocol" title="协议文件目录"/>
    </system-path>

    <!-- 插件包配置清单 -->

    <!-- 基础引擎库 -->
    <package name="com.yoseasoft.gooasset" displayName="GooAsset" title="Goo资产管理框架" required="true">
        <git-repository url="%REPO_URL%/GooAsset.git"/>
    </package>
    <package name="com.yoseasoft.novaframework" displayName="NovaFramework" title="Nova引擎框架" required="true">
        <git-repository url="%REPO_URL%/NovaFramework.git"/>
        <dependencies>
            <reference-package>com.yoseasoft.gooasset</reference-package>
            <reference-package>com.novaframework.unity.unitask</reference-package>
        </dependencies>
    </package>
    <package name="com.novaframework.unity.core.configure" displayName="NovaFramework.Configure" title="Nova引擎配置核心库" required="true">
        <git-repository url="%REPO_URL%/com.novaframework.unity.core.configure.git"/>
    </package>
    <package name="com.novaframework.unity.core.boot" displayName="NovaFramework.Boot" title="Nova引擎启动核心库" required="true">
        <git-repository url="%REPO_URL%/com.novaframework.unity.core.boot.git"/>
        <dependencies>
            <reference-package>com.novaframework.unity.core.configure</reference-package>
        </dependencies>
    </package>

    <!-- 第三方工具库 -->
    <package name="com.novaframework.unity.unitask"
             displayName="NovaFramework.UniTask"
             title="UniTask工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.unitask.git"/>
    </package>
    <package name="com.novaframework.unity.litjson"
             displayName="NovaFramework.LitJson"
             title="LitJson工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.litjson.git"/>
    </package>
    <package name="com.novaframework.unity.sharpziplib"
             displayName="NovaFramework.SharpZipLib"
             title="SharpZipLib工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.sharpziplib.git"/>
    </package>
    <package name="com.novaframework.unity.luban"
             displayName="NovaFramework.Luban"
             title="Luban工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.luban.git"/>
    </package>
    <package name="com.novaframework.unity.protobuf"
             displayName="NovaFramework.Protobuf"
             title="Protobuf工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.protobuf.git"/>
        <repulsions>
            <reference-package>com.novaframework.unity.streambuf</reference-package>
        </repulsions>
    </package>
    <package name="com.novaframework.unity.streambuf"
             displayName="NovaFramework.Streambuf"
             title="Streambuf工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.streambuf.git"/>
        <repulsions>
            <reference-package>com.novaframework.unity.protobuf</reference-package>
        </repulsions>
    </package>
    <package name="com.novaframework.unity.fairygui"
             displayName="NovaFramework.FairyGUI"
             title="FairyGUI工具库">
        <git-repository url="%REPO_URL%/com.novaframework.unity.fairygui.git"/>
    </package>

    <!-- 教程实例库 -->
    <package name="com.gameframework.unity.sample"
             displayName="GameFramework.Sample"
             title="Nova教程库"
             description="针对Nova框架的特性以及调度方式，提供一些教程案例作为使用入门的参考">
        <git-repository url="%REPO_URL%/com.gameframework.unity.sample.git"/>
        <assembly-definition name="Game.Sample" order="211">
            <loadable-strategy>Module</loadable-strategy>
            <loadable-strategy>Compile</loadable-strategy>
            <loadable-strategy>Tutorial</loadable-strategy>
        </assembly-definition>
    </package>

    <!-- 游戏启动器 -->
    <package name="com.gameframework.unity.launcher"
             displayName="GameFramework.Launcher"
             title="Nova启动模版"
             description="针对Nova框架提供一套默认的启动流程代码模版，可以基于这套模版定制个性化的启动流程">
        <git-repository url="%REPO_URL%/com.gameframework.unity.launcher.git"/>
        <dependencies>
            <reference-package>com.novaframework.unity.core.configure</reference-package>
            <reference-package>com.novaframework.unity.sharpziplib</reference-package>
        </dependencies>
    </package>

    <!-- 模块支持库 -->
    <package name="com.gameframework.unity.module.protocol.protobuf"
             displayName="GameFramework.Module.Protocol.Protobuf"
             title="Protobuf服务模块"
             description="提供基于Protobuf协议解析及操作码注册管理">
        <git-repository url="%REPO_URL%/com.gameframework.unity.module.protocol.protobuf.git"/>
        <assembly-definition name="Game.Module.Protocol.Protobuf" order="111">
            <loadable-strategy>Module</loadable-strategy>
        </assembly-definition>
        <dependencies>
            <reference-package>com.novaframework.unity.protobuf</reference-package>
        </dependencies>
        <repulsions>
            <reference-package>com.gameframework.unity.module.protocol.streambuf</reference-package>
        </repulsions>
    </package>
    <package name="com.gameframework.unity.module.protocol.streambuf"
             displayName="GameFramework.Module.Protocol.Streambuf"
             title="Streambuf服务模块"
             description="提供基于Streambuf协议解析及操作码注册管理">
        <git-repository url="%REPO_URL%/com.gameframework.unity.module.protocol.streambuf.git"/>
        <assembly-definition name="Game.Module.Protocol.Streambuf" order="112">
            <loadable-strategy>Module</loadable-strategy>
        </assembly-definition>
        <dependencies>
            <reference-package>com.novaframework.unity.streambuf</reference-package>
        </dependencies>
        <repulsions>
            <reference-package>com.gameframework.unity.module.protocol.protobuf</reference-package>
        </repulsions>
    </package>
    <package name="com.gameframework.unity.module.view.fairygui"
             displayName="GameFramework.Module.View.FairyGUI"
             title="FairyGUI服务模块"
             description="封装FairyGUI窗口加载及组件访问服务，对外提供UI操作的便捷访问接口">
        <git-repository url="%REPO_URL%/com.gameframework.unity.module.view.fairygui.git"/>
        <assembly-definition name="Game.Module.View.Fairygui" order="121">
            <loadable-strategy>Module</loadable-strategy>
            <loadable-strategy>Compile</loadable-strategy>
        </assembly-definition>
        <dependencies>
            <reference-package>com.novaframework.unity.fairygui</reference-package>
        </dependencies>
        <assets-path>GUI_PATH</assets-path>
    </package>
    <package name="com.gameframework.unity.module.view.ugui"
             displayName="GameFramework.Module.View.UGUI"
             title="UGUI服务模块"
             description="封装UGUI窗口加载及组件访问服务，对外提供UI操作的便捷访问接口">
        <git-repository url="%REPO_URL%/com.gameframework.unity.module.view.ugui.git"/>
        <assembly-definition name="Game.Module.View.Ugui" order="122">
            <loadable-strategy>Module</loadable-strategy>
        </assembly-definition>
        <assets-path>GUI_PATH</assets-path>
    </package>

    <!-- 业务定制库 -->
    <package name="com.gameframework.unity.module.asset.namesearcher"
             displayName="GameFramework.Module.Asset.NameSearcher"
             title="Goo资产名称检索器"
             description="提供基于Goo资产打包规则下的名称检索，对外提供基于名称进行资源访问的扩展操作的便捷访问接口">
        <git-repository url="%REPO_URL%/com.gameframework.unity.module.asset.namesearcher.git"/>
        <assembly-definition name="Game.Module.Asset.NameSearcher" order="131">
            <loadable-strategy>Module</loadable-strategy>
        </assembly-definition>
        <dependencies>
            <reference-package>com.yoseasoft.gooasset</reference-package>
            <reference-package>com.novaframework.unity.litjson</reference-package>
        </dependencies>
    </package>
</root>
